version: '3'
services:
  server1:
    image: localhost/server:latest
    networks:
      - app-network

  server2:
    image: localhost/server:latest
    networks:
      - app-network

  nginx:
    image: 10.244.226.233:5001/images/nginx
    ports:
      - "7777:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
